Develop
serj2206/java-explore-with-me pull request #2
Opened 2022-11-28 21:41 UTC by serj2206

2022-11-30 20:24 UTC, sergeymamonov requested changes

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/resources/schema.sql
> +    annotation VARCHAR NOT NULL,
В скриптах sql размер varchar должен быть ограничен.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/common/FromSizeRequest.java
> +        super(offset / size, size, sort);
А если пользователь size = 0 передаст? Лучше валидировать входные параметры в сервисе.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/conrollers/AdminController.java
> +        return;
Если метод ничего не возвращает, то слово return можно не писать. Посмотрите весь код. Встречается несколько таких случаев.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/model/compilation/mapper/CompilationMapper.java
> +        Compilation compilation = Compilation.builder()
Можно сразу возвращать 
return Compilation.builder()
                .title(newCompilationDto.getTitle())
                .pinned(newCompilationDto.isPinned())
                .events(events)
                .build();
Без создания промежуточной переменной.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/model/event/mapper/EventMapper.java
> +        Event event = Event.builder()
Аналогично, сразу вернуть, без создания переменной.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/model/user/mapper/UserMapper.java
> +        User user = User.builder()
Аналогично, сразу вернуть, без создания переменной.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/model/user/mapper/UserMapper.java
> +    public static UserShortDto toUserShortDto(User user) {
Этот метод где-то используется?

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/repository/CategoryRepository.java
> +    Category findByName(String name);
Этот метод где-то используется?

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/repository/CompilationRepository.java
> +
Лучше убрать лишние пустые строки.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/repository/EventRepository.java
> +    //Event fndOne(BooleanExpression eq);
В проекте не должно быть закомментированного кода.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/AdminService.java
> +                .get();
Перед тем, как вызывать у Optional метод get, нужно проверить содержимое Optional на null. Для этого есть специальные методы у Optional.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/AdminService.java
> +                .orElseThrow(() -> new NoSuchElementException(String.format("Событие не найдено")));
String.format("Событие не найдено") - а почему просто строку не передать?

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/PrivateService.java
> +        User user = userRepository.findById(userId)
Далее переменная user нигде не используется. Ниже по коду аналогичные места.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/PrivateService.java
> +                .orElseThrow(() -> new NoSuchElementException(String.format("Событие не найдено")));
Зачем здесь использовать String.format?

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/PrivateService.java
> +        List<ParticipationRequestDto> participationRequestDtoList =
Можно сразу вернуть, без создания переменной.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/PublicService.java
> +        EventFullDto eventFullDto = EventMapper.toEventFullDto(event, views, confirmedRequests);
Не нужно создавать лишнюю переменную.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/PublicService.java
> +                .get();
Проверить, перед вызовом get().

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/StatsService.java
> +                .get()
Перед вызовом get() проверить содержимое.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/StatsService.java
> +        List<ViewStats> viewStatsList = publicClient.findStats(
Лишняя переменная.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/StatsService.java
> +                .get()
Проверить.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/StatsService.java
> +        List<ViewStats> viewStatsList = publicClient.findStats(
Лишняя переменная.

2022-11-30 20:24 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/statsserver/controllers/StatsController.java
> +        return;
Лишний return.

2022-11-30 20:24 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/statsserver/model/mapper/EndpointMapper.java
> +        EndpointHit endpointHit = EndpointHit.builder()
Лишняя переменная.

2022-11-30 20:24 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/statsserver/model/mapper/EndpointMapper.java
> +    public static ViewStats toViewsStats(EndpointHit endpointHit, int hit) {
Используется ли где-то этот метод?

2022-11-30 20:24 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/statsserver/service/StatsService.java
> +        return;
Лишнее.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/client/PublicClient.java
> +        List<ViewStats> viewStatsList = (List<ViewStats>) entity.getBody();
Лишняя переменная.

2022-11-30 20:24 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/service/StatsService.java
> +                .getEventDate();                ;
Лишняя точка с запятой.

2022-12-01 21:46 UTC, serj2206 commented
Здравствуйте Сергей.
Постарался исправить ошибки по вашим замечаниям:

1. Скриптах sql установлен размер varchar.
2. Удалены return, когда метод ничего не возвращает. 
3. Там где можно, удалены промежуточные переменные.
4. Удален не используемые методы.
5. Удалены не используемые переменные.

Замечание про size в вспомогательном классе я не совсем понял. Валидация size и from у меня происходит в контроллерах с помощью javax.validation. Правильно ли я понял, что вы предлагаете перенести ее в методы серверов, а из контроллеров валидацию этих параметров убрать?

2022-12-02 21:36 UTC, sergeymamonov approved these changes
Да, дополнительной валидации size не нужно. Достаточно той, что в контроллере. В одном месте лишний return в методе, который возвращает void (можно найти поиском по проекту по void). И не везде избавились от лишний переменных при возврате результата из метода.

2022-12-02 21:36 UTC, sergeymamonov commented on stats/src/main/java/ru/practicum/statsserver/controllers/StatsController.java
> +        return;
Почему оставлен return?

2022-12-02 21:36 UTC, sergeymamonov commented on ewm/src/main/java/ru/practicum/ewmservice/client/PublicClient.java
> +        List<ViewStats> viewStatsList = (List<ViewStats>) entity.getBody();
Можно сразу вернуть return (List<ViewStats>) entity.getBody();

2022-12-03 08:28 UTC, merged